# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevEnv
    jobs:
      - job: FirstJob
        steps:
          - bash: echo ths is DevStage
  - stage: TestEnv
    jobs:
      - job: SecondJob
        steps:
          - bash: echo "This is Test Env"
  - stage: NonProdEnv
    jobs:
      - job: thirdJob
        steps:
          - bash: echo "This is NonProd Env"
  - stage: ProdEnv
    jobs:
      - job: FourthJob
        steps:
          - bash: echo "this is Prod Env"