# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# strategy:
#   matrix:
#     linux: 
#         OpratingSystem : ubuntu-latest
#     mac: 
#       OpratingSystem : macos-latest



pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevStage
    jobs:
      - job: DevJobs
        steps:
          - bash: echo "Deploy the Code in Dev Env"
  - stage: TestStage
    jobs:
      - deployment: TestDeploy
        environment: TestEnv
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello This is Test Deployment
  - stage: QAStage
    jobs:
      - deployment: QADeploy
        environment: QA Env
        strategy:
         runOnce:
          deploy:
            steps:
              - script: echo Hello this is QA Deployment
  - stage: Preprodstage
    jobs:
      - deployment: PreProd
        environment: PreProd Env
        dependsOn: DevStage
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo Hello this is PreProd Deployment
         
  - stage: NonProdStage
    jobs:
      - deployment: NonProd
        environment: NonProd Env
        dependsOn:
        - DevStage
        strategy:
          runOnce:
           deploy:
             steps:
               - script: echo Hello this is NonProd Deployment
  - stage: ProdStage
    jobs:
      - deployment: Prod
        environment: Prod Env
        dependsOn: Preprodstage
        strategy:
          runOnce:
           deploy:
             steps:
               - script: echo Hello this is Prod Deployment





